### ISSUE TITLE
are you planning a pypi release?

### ISSUE THREAD

**Issue by ferdinandyb** [jktr/matplotlib-backend-kitty#4]
Would be nice to be able to `pip install` this.

**Comment by jktr** [comment]
I didn't originally plan on a pypi release. However, as several users have requested one I've attempted to package it and put it up as [`matplotlib-backend-kitty`](https://pypi.org/project/matplotlib-backend-kitty/). It's based on the `dev/pip-package` branch.

I appreciate it if you could confirm that the package works as expected, as I'm not too familiar with the python packaging process.

**Comment by ferdinandyb** [comment]
It works as expected, thanks!
